### ISSUE TITLE
Seems to crash for courses containing specific characters

### ISSUE THREAD

**Issue by Sebastian-GHub** [MrDrache333/Java-StudIP-Telegram-Bot#12]
Looks like the character ":" breaks it.
Edit: Also crashes on "*".

![image](https://user-images.githubusercontent.com/96473509/194954135-2cd2a5ac-7ede-464d-95d7-8d89da94e965.png)

**Comment by MrDrache333** [comment]
Release wasn’t Updated after the latest Push. Now it’s up to date. Please try again.
